form:
  tabs:
    - name: tabTitle
      label: Header
      fields:
        - name: title
          class: info.magnolia.ui.form.field.definition.TextFieldDefinition
          label: Judul
        - name: text
          class: info.magnolia.ui.form.field.definition.RichTextFieldDefinition
          label: Text
        - name: page
          class: info.magnolia.ui.form.field.definition.LinkFieldDefinition
          targetWorkspace: website
          appName: pages
          identifierToPathConverter:
            class: info.magnolia.ui.form.field.converter.BaseIdentifierToPathConverter
          label: Link Halaman	
    - name: tabImage
      label: Icon
      fields:
        - name: image
          class: info.magnolia.ui.form.field.definition.LinkFieldDefinition
          targetWorkspace: dam
          appName: assets
          identifierToPathConverter:
            class: info.magnolia.dam.app.assets.field.translator.AssetCompositeIdKeyTranslator
          contentPreviewDefinition:
            contentPreviewClass: info.magnolia.dam.app.ui.field.DamFilePreviewComponent
          label: Icon
actions:
  commit:
    class: info.magnolia.ui.admincentral.dialog.action.SaveDialogActionDefinition
  cancel:
    class: info.magnolia.ui.admincentral.dialog.action.CancelDialogActionDefinition